easy_admin:
    site_name: 'Administration Waloude'
    user:
        display_name: true
        display_avatar: true
    entities:
        # List the entity class name you want to manage
        - App\Entity\Souscripteur
        - App\Entity\Beneficiaire
        - App\Entity\Conjoint
        - App\Entity\Enfant
        - App\Entity\User
        - App\Entity\Faq
        - App\Entity\Team
        - App\Entity\Pages

    list:
      actions: 
        - { name: 'show', icon: 'eye', label: false, title: 'Voir' }
        - { name: 'edit', icon: 'pencil', label: false, title: 'Modifier' }
        - { name: 'delete', icon: 'trash', label: false, title: 'Supprimer' }

